using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemyController : MonoBehaviour
{
    // Public variables
    public float speed;
    public bool vertical;
    public float changeTime = 3.0f;

    // Private variables
    Rigidbody2D rigidbody2D;
    Animator animator; 
    float timer;
    int direction = 1;

    // Start is called before the first frame update
    void Start()
    {
        animator = GetComponent<Animator>();
      rigidbody2D = GetComponent<Rigidbody2D>();
        timer = changeTime;
    }

    // Update is called once per frame
    void Update()
    {
        timer-= Time.deltaTime;
        if (timer < 0)
        {
            direction = -direction;
            timer = changeTime;
        }
    }
    // FixedUpdate has the same call rate as the physics system
        void FixedUpdate()  
        {
           
            Vector2 position = rigidbody2D.position;
            if (vertical)
            {
            animator.SetFloat("Move X", 0);
            animator.SetFloat("Move Y", direction);
            position.y = position.y + Time.deltaTime * speed * direction;
            }
            else
            {
                animator.SetFloat("Move X", direction);      
                animator.SetFloat("Move Y", 0);
                position.x = position.x + Time.deltaTime * speed * direction;
            }
            rigidbody2D.MovePosition(position);
        }
    void OnTriggerEnter2D(Collider2D other)
    {
        PlayerController player = other.gameObject.GetComponent<PlayerController>();
        if (player != null)
        {
            player.ChangeHealth(-1);
        }
    }
}
